{% set name = "pip2pi" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wolever/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5fe6ad966805a28e1b5f886bcf453cab5fd209ac5a13479f7a456e5d42e12b24

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dir2pi = libpip2pi.commands:dir2pi
    - pip2pi = libpip2pi.commands:pip2pi
    - pip2tgz = libpip2pi.commands:pip2tgz

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pip
    - setuptools

test:
  commands:
    - pip2pi --help
    - dir2pi --help
    - pip2tgz --help

about:
  home: https://github.com/wolever/pip2pi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: pip2pi builds a PyPI-compatible package repository from pip requirements

extra:
  recipe-maintainers:
    - marcelotrevisani
