travis:
  secure:
    BINSTAR_TOKEN: JJuwpTjBFcEwtAzko73PjNZHHnLaJJPDNhediVg9o2qyPDZkIizDVHWKVcJrfKfsGwB+ESlMD7BpqUOTJghq1ydC7XRCShdsALRaCwtEhlLkr/vOtQW0rt4m+Kmj+4M1DYTu4DNq14A/KQq63ONRrUhDaGTc903qGD5IKwtua5hlQyVl9rLuABuDT0+yvTLT8YaP97DMlfe16Oz7gBPtHJwPl6XbdOXiMHi/vgfORIKRtO8aK14CpwW+Dh+ekVSi0ON5Y0e3OLQudbnxYNtNu0NBqjz2Glh8g+4PSQbXNuc6tFLQ539HoHMXQUrHGAVm/ZK8gt/lyz55ZUfqKmCfrCh/iNSb88ltI1G/SAKJow2AoRlHEcXi9f6Q31yltSgDtvIdHcYXk2mjDH2AVcOhJUqLmPUuJzj+mYB4ytmLphIjieBFwROtxCrY0BKeLQ3NTXhD9S8U+6H/qJRgwgrx6uAOuKl6V1VtGoZSa+/SXIha34YDdh2At+Lx858S5V7WgTwaLh5V+mHxCYW6kkwxcMFiL1Xe1xowHPuJoID6WhTG2ctyu5iwpm/mFubh4jrY0UsvrQC/PXGfyE1+qKob4TJS1evX33R4jhndnMs6aX5DMkgQdGygXKvjdyeCmD8TXnJLjUHwCewg2UIal+kX+mMvcf98x6Zb/my8H8RSEM4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
